

CREATE TABLE IF NOT EXISTS incomes(
  id INT PRIMARY KEY AUTO_INCREMENT,
  montant DECIMAL(10,2),
  date DATE DEFAULT (CURRENT_TIME),
  description TEXT,
  category VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS expences(
  id INT PRIMARY KEY AUTO_INCREMENT,
  montant DECIMAL(10,2),
  date DATE DEFAULT (CURRENT_TIME),
  description TEXT,
  category VARCHAR(255)
);

ALTER TABLE incomes ADD userID INT;
ALTER TABLE expences ADD userID INT;

CREATE TABLE IF NOT EXISTS users(
 id int PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(25),
 email VARCHAR(100) UNIQUE,
 password VARCHAR(255)
);